import { AllWorklogModel } from 'src/app/models/worklog.model';
import { Lang } from 'src/app/models/language.model';

export const WORKLOG: AllWorklogModel = {
  [Lang.en]: [
    { description: 'Maksim Kirylka' },
    { time: '2', description: 'Split the major task into small subtasks' },
    { time: '4', description: 'Navigation bar (navigation mobile menu, header, language selector)' },
    { time: '4', description: 'Create json(s) with architects (by, en, ru)' },
    { time: '5', description: 'Author page (description, timeline, video, gallery)' },
    { time: '1', description: 'UI translations' },
    { time: '6', description: 'Code review' },
    { description: 'Alexy Morozov' },
    { time: '4', description: 'Languages support' },
    { time: '5', description: 'Translation' },
    { time: '6', description: 'Design & styles' },
    { time: '6', description: 'Code review' },
    { description: 'Raman Haiduchyk' },
    { time: '6', description: 'Authors page' },
    { time: '4', description: 'Search widget' },
    { time: '5', description: 'Author page' },
    { time: '6', description: 'Code review' },
    { description: 'Petro Yuskiv' },
    { time: '2', description: 'Primary structure of the project' },
    { time: '4', description: 'WorkLog page' },
    { time: '4', description: '"Author of the day" component' },
    { time: '6', description: 'Self-Evaluation component' },
    { time: '2', description: '404 page' },
    { time: '6', description: 'Code review' },
    { description: 'Andrey Knyshenko' },
    { time: '4', description: 'Team page' },
    { time: '6', description: 'Main page' },
    { time: '6', description: 'Design & styles' },
    { time: '6', description: 'Code review' },
  ],
  [Lang.ru]: [
    { description: 'Максим Кирилко' },
    { time: '2', description: 'Разделить основную задачу на мелкие подзадачи' },
    { time: '4', description: 'Панель навигации (навигация мольного режима, заголовок, выбор языков)' },
    { time: '4', description: 'Создать json с архитекторами (by, en, ru)' },
    { time: '5', description: 'Страница автора (описание, биография, видео, галерея)' },
    { time: '1', description: 'Перевод UI' },
    { time: '6', description: 'Ревью кода' },
    { description: 'Алексей Морозов' },
    { time: '4', description: 'Языковая поддержка' },
    { time: '5', description: 'Перевод' },
    { time: '6', description: 'Дизайн & стили' },
    { time: '6', description: 'Ревью кода' },
    { description: 'Роман Хайдучик' },
    { time: '6', description: 'Страница авторов' },
    { time: '4', description: 'Поисковый виджет' },
    { time: '5', description: 'Страница автора' },
    { time: '6', description: 'Ревью кода' },
    { description: 'Петро Юськив' },
    { time: '2', description: 'Базовая структура проекта' },
    { time: '4', description: 'Страница Рабочего журнала' },
    { time: '4', description: 'Компонент "Автор дня"' },
    { time: '6', description: 'Компонент "Самооценки"' },
    { time: '2', description: 'Страница 404' },
    { time: '6', description: 'Ревью кода' },
    { description: 'Андрей Книшенко' },
    { time: '4', description: 'Страница команды' },
    { time: '6', description: 'Главная страница' },
    { time: '6', description: 'Дизайн & стили' },
    { time: '6', description: 'Ревью кода' },
  ],
  [Lang.by]: [
    { description: 'Максім Кірылка' },
    { time: '2', description: 'Разделить основную задачу на мелкие подзадачи' },
    { time: '4', description: 'Падзяліць асноўную задачу на дробныя подзадачи' },
    { time: '4', description: 'Стварыць json з архітэктарамі (by, en, ru)' },
    { time: '5', description: 'Старонка аўтара (апісанне, біяграфія, відэа, галерэя)' },
    { time: '1', description: 'Пераклад UI' },
    { time: '6', description: 'Рэвью кода' },
    { description: 'Аляксей Марозаў' },
    { time: '4', description: 'Моўная падтрымка' },
    { time: '5', description: 'Пераклад' },
    { time: '6', description: 'Дызайн & стылі' },
    { time: '6', description: 'Рэвью кода' },
    { description: 'Роман Хайдучик' },
    { time: '6', description: 'Старонка аўтараў' },
    { time: '4', description: 'Пошукавы віджэт' },
    { time: '5', description: 'Старонка аўтара' },
    { time: '6', description: 'Рэвью кода' },
    { description: 'Петро Юськив' },
    { time: '2', description: 'Базавая структура праекта' },
    { time: '4', description: 'Старонка Працоўнага часопіса' },
    { time: '4', description: 'Кампанент "Аўтар дня"' },
    { time: '6', description: 'Кампанент "самаацэнкі"' },
    { time: '2', description: 'Старонка 404' },
    { time: '6', description: 'Рэвью кода' },
    { description: 'Андрей Книшенко' },
    { time: '4', description: 'Старонка каманды' },
    { time: '6', description: 'Галоўная старонка' },
    { time: '6', description: 'Дызайн & стылі' },
    { time: '6', description: 'Рэвью кода' },
  ],
};
